FROM node:12 AS builder

WORKDIR /build

COPY app/ .

RUN npm install

RUN npm run build


FROM nginx:latest

COPY --from=builder /build/dist /www

COPY deployments/nginx_app.conf /etc/nginx/nginx.conf

EXPOSE 3000
