sudo: true

services: docker

branches:
  only:
    - dev
    - ci

jobs:
  include:
    - stage: build docker image
      script:
        - bash deployments/ci/build.sh
    - stage: push docker image
      script:
        - bash deployments/ci/push.sh
