version: "3"

services:
  build:
    build:
      context: ../
      dockerfile: docker/Dockerfile-build
    volumes:
      - "../frontend:/app"

  build_chat:
    build:
      context: ../
      dockerfile: docker/Dockerfile-build
    volumes:
      - "../chat:/app"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - build
      - build_chat
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "../frontend/dist:/www_app"
      - "../chat/dist:/www_chat"
    ports:
      - 3001:3001