version: "3"

services:
  build_app:
    build:
      context: ../
      dockerfile: docker/Dockerfile-build
    volumes:
      - "../frontend:/app"

  build_chat:
    build:
      context: ../
      dockerfile: docker/Dockerfile-build
    volumes:
      - "../chat:/app"

  nginx_app:
    image: nginx:latest
    restart: always
    depends_on:
      - build_app
    volumes:
      - "./nginx_app.conf:/etc/nginx/nginx.conf:ro"
      - "../frontend/dist:/www"
    ports:
      - 3001:3001

  nginx_chat:
    image: nginx:latest
    restart: always
    depends_on:
      - build_chat
    volumes:
      - "./nginx_chat.conf:/etc/nginx/nginx.conf:ro"
      - "../chat/dist:/www"
    ports:
      - 3002:3002
