version: "3"

services:
  build:
    build:
      context: ../
      dockerfile: docker/Dockerfile-build
    volumes:
      - "../frontend:/app"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - build
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../frontend/dist:/www"
    ports:
      - 3001:3001